apiVersion: apps/v1
kind: Deployment
metadata:
  name: yair-api-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yair-api
  template:
    metadata:
      labels:
        app: yair-api
    spec:
      containers:
      - name: python-container
        image: python:3.9-slim
        command: ["/bin/sh", "-c", "sleep 3600"]