apiVersion: apps/v1
kind: Deployment
metadata:
  name: yair-api-python
spec:
  replicas: 15
  selector:
    matchLabels:
      app: yair-api
  template:
    metadata:
      labels:
        app: yair-api
    spec:
      containers:
      - name: python-container
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "awk 'BEGIN { for(i=0;i<1500000;i++) a[i]=\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"; while(1) {} }'"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"