apiVersion: apps/v1
kind: Deployment
metadata:
  name: yair-api-python
spec:
  replicas: 15
  selector:
    matchLabels:
      app: yair-api
  template:
    metadata:
      labels:
        app: yair-api
    spec:
      containers:
      - name: python-container
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "apk update && apk add stress && stress --cpu 1 --vm 1 --vm-bytes 250M"]
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"